services:
  php-container:
    build: ./main/
    container_name: php-app
    ports:
      - "8000:80"

  db-container:
    build: ./db/
    image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: "hive"
    ports:
      - "3306:3306"

  ai-container:
    build:
      context: .
    ports:
      - "5000:5000"

  jenkins:
    build: ./jenkins/
    image: jenkins
    ports:
      - "8080:8080"
    networks:
      - jenkins
    volumes:
      - jenkins_data:/var/jenkins_home

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - jenkins
    volumes:
      - sonarqube_data:/opt/sonarqube/data

networks:
  jenkins:
    driver: bridge

volumes:
  sonarqube_data:
  jenkins_data:
