pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                checkout scm
            }
        }

        stage('SonarQube') {
            steps {
                script { scannerPath = tool 'SonarQube' }
                withSonarQubeEnv('SonarQube') {
                    sh "${scannerPath}/bin/sonar-scanner -Dsonar.projectKey=sonarqube"
                }
            }
        }
    }
}


